# Generated by Django 4.2.2 on 2023-07-12 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.PositiveIntegerField()),
            ],
        ),
    ]
