# Generated by Django 4.2.2 on 2023-07-12 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_producto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.RenameField(
            model_name='paquete',
            old_name='codigo',
            new_name='id',
        ),
    ]
