# Generated by Django 4.2.2 on 2023-07-12 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_producto_rename_codigo_paquete_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='imagen',
            field=models.ImageField(null=True, upload_to='paquetes'),
        ),
    ]
